apiVersion: management.cattle.io/v3
kind: Feature
metadata:
  name: multi-cluster-management
spec:
  value: true
status:
  default: false
  description: Multi-cluster provisioning and management of Kubernetes clusters.
  dynamic: true
