{{- if eq .Values.stringflag "on" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment1
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: Always
        command:
         - sleep
         - "3600"
{{- end }}
---
{{- if gt .Values.intflag 99.0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment2
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: Always
        command:
         - sleep
         - "3600"
{{- end }}
---
{{- if .Values.boolflag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment3
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: Always
        command:
         - sleep
         - "3600"
{{- end }}


