apiVersion: v1
name: enterprise-cluster-manager-feature
description: Install Enterprise Cluster Manager feature to manage Kubernetes clusters across providers.
version: 0.1.100
appVersion: 0.1.100
home: https://rancher.com
icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
keywords:
  - rancher
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
annotations:
  catalog.rancher.io/certified: rancher
  catalog.rancher.io/namespace: cattle-system
  catalog.rancher.io/release-name: enterprise-cluster-manager-feature
