name: CI-push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run CI scripts
      run: |-
        sudo make ci

    - uses: stefanzweifel/git-auto-commit-action@480e111bf8274f3bbd429aef51504f71c808e3e4
      with:
        commit_message: Generated changes
  sync:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@bda99324450c6c9cebcb15c5566126fb55131041
      with:
        source_repo: "https://github.com/rancher/charts.git"
        source_branch: "dev-v2.5"
        destination_branch: "gh-pages"
